services:
  oct-server-local:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8100:8100
    container_name: oct-server-local
    tty: true
    environment:
      - OCT_ACTIVATE_SIMPLE_LOGIN=true
