images:
- $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
steps:
- args:
  - build
  - -t
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - .
  - -f
  - Dockerfile
  id: Build
  name: gcr.io/cloud-builders/docker
- args:
  - push
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  id: Push
  name: gcr.io/cloud-builders/docker
- args:
  - run
  - services
  - update
  - $_SERVICE_NAME
  - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - --region=$_DEPLOY_REGION
  - --service-account=%SERVICE_ACCOUNT%
  - --port=8100
  - --cpu=1
  - --memory=1Gi
  - --cpu-throttling
  - --max-instances=1
  entrypoint: gcloud
  id: Deploy
  name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
substitutions:
  _AR_HOSTNAME: %DEPLOY_REGION%-docker.pkg.dev
  _DEPLOY_REGION: %DEPLOY_REGION%
  _SERVICE_NAME: %SERVICE_NAME%
